version: '3.8'
services:
  api:
    container_name: api
    build: .
    tty: true
    ports:
      - '8000:8000'
    volumes:
      - type: bind
        source: .
        target: /api
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
volumes:
  redis:
    driver: local
